export enum AuditLogAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  INVITE_CREATED = "INVITE_CREATED",
  INVITE_ACCEPTED = "INVITE_ACCEPTED",
  ROLE_CHANGED = "ROLE_CHANGED",
  MEMBER_REMOVED = "MEMBER_REMOVED",
  STATUS_CHANGED = "STATUS_CHANGED",
  DEADLINE_CHANGED = "DEADLINE_CHANGED",
  TASK_CREATED_VIA_TELEGRAM = "TASK_CREATED_VIA_TELEGRAM",
  TASK_CREATED_VIA_WEBHOOK = "TASK_CREATED_VIA_WEBHOOK",
}

